spring:
  application:
    name: '@project.artifactId@'
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

application:
  http-client:
    jwt-token:
      base-url: http://localhost:8080/auth/jwt/v1/
    person:
      base-url: http://localhost:8081/application/pragma/training/v1/

server:
  port: 9020
  error:
    include-message: always

logging:
  level:
    com.co.pragma.training.service.app: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka/'